lib/shenanigans_web/router.ex
defmodule ShenanigansWeb.Router do
  use ShenanigansWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :feed do
    plug :accepts, ["xml"]
  end

  scope "/", ShenanigansWeb do
    pipe_through :browser

    get "/", BlogController, :index
    get "/:slug", BlogController, :show, as: :post
    # get "/sitemap.xml", SitemapController, :index
    get "/tags/:tag", TagController, :index
  end
end

lib/shenanigans/application.ex
defmodule Shenanigans.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the endpoint when the application starts
      ShenanigansWeb.Endpoint
      # Starts a worker by calling: Shenanigans.Worker.start_link(arg)
      # {Shenanigans.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Shenanigans.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ShenanigansWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/shenanigans/blog.ex
defmodule Shenanigans.Blog do
  @moduledoc false

  alias Shenanigans.Blog.Post

  for app <- [:earmark, :makeup_elixir] do
    Application.ensure_all_started(app)
  end

  defmodule NotFoundError do
    defexception [:message, plug_status: 404]
  end

  posts_path =
    "posts/**/*.md"
    |> Path.wildcard()
    |> Enum.sort()

  posts =
    for post_path <- posts_path do
      @external_resource Path.relative_to_cwd(post_path)
      Post.parse!(post_path)
    end

  @posts Enum.sort_by(posts, & &1.date, {:desc, Date})
  @tags Enum.flat_map(posts, & &1.tags) |> Enum.uniq() |> Enum.sort()

  @doc """
  Returns a list of posts.

  ## Examples

      iex> all_posts()
      [%Post{}, ...]

  """
  def all_posts, do: @posts

  @doc """
  Returns a post by the given slug

  ## Examples

      iex> get_post("02-25-first-post")
      %Post{}

  """
  def get_post(slug), do: Enum.filter(@posts, &(&1.id == slug)) |> List.first()

  @doc """
  Returns a list of tags

  ## Examples

      iex> all_tags()
      ["elixir", "elm"]

  """
  def all_tags, do: @tags

  @doc """
  Returns a list of posts that have the given tag

  ## Examples

      iex> get_posts_by_tag!("elixir")
      [%Post{}, %Post{}]

      iex> get_posts_by_tag!(nil)
      NotFoundError

  """
  def get_posts_by_tag!(tag) do
    case Enum.filter(@posts, &(tag in &1.tags)) do
      [] -> raise NotFoundError, "posts with tag=#{tag} not found"
      posts -> posts
    end
  end
end

lib/shenanigans/blog/highlighter.ex
defmodule Shenanigans.Blog.Highlighter do
  @moduledoc """
  Performs code highlighting.
  """

  # If new lexers are available, add them here:
  defp pick_language_and_lexer(""), do: {"elixir", Makeup.Lexers.ElixirLexer, []}

  defp pick_language_and_lexer(lang) do
    case Makeup.Registry.fetch_lexer_by_name(lang) do
      {:ok, {lexer, opts}} ->
        {lang, lexer, opts}

      :error ->
        {lang, nil, []}
    end
  end

  @doc """
  Highlights all code block in an already generated HTML document.
  """
  def highlight(html, opts \\ []) do
    Regex.replace(
      ~r/<pre><code(?:\s+class="(\w*)")?>([^<]*)<\/code><\/pre>/,
      html,
      &highlight_code_block(&1, &2, &3, opts)
    )
  end

  defp highlight_code_block(full_block, lang, code, outer_opts) do
    case pick_language_and_lexer(lang) do
      {_language, nil, _opts} -> full_block
      {language, lexer, opts} -> render_code(language, lexer, opts, code, outer_opts)
    end
  end

  defp render_code(lang, lexer, lexer_opts, code, opts) do
    highlight_tag = Keyword.get(opts, :highlight_tag, "span")

    highlighted =
      code
      |> unescape_html()
      |> IO.iodata_to_binary()
      |> Makeup.highlight_inner_html(
        lexer: lexer,
        lexer_options: lexer_opts,
        formatter_options: [highlight_tag: highlight_tag]
      )

    ~s(<pre><code class="nohighlight makeup #{lang}">#{highlighted}</code></pre>)
  end

  entities = [{"&amp;", ?&}, {"&lt;", ?<}, {"&gt;", ?>}, {"&quot;", ?"}, {"&#39;", ?'}]

  for {encoded, decoded} <- entities do
    defp unescape_html(unquote(encoded) <> rest) do
      [unquote(decoded) | unescape_html(rest)]
    end
  end

  defp unescape_html(<<c, rest::binary>>) do
    [c | unescape_html(rest)]
  end

  defp unescape_html(<<>>) do
    []
  end
end

lib/shenanigans/blog/post.ex
defmodule Shenanigans.Blog.Post do
  @moduledoc false

  alias Shenanigans.Blog.Highlighter

  @enforce_keys [:id, :author, :title, :body, :description, :tags, :date]
  defstruct [:id, :author, :title, :body, :description, :tags, :date]

  def parse!(filename) do
    # Get the last two path segments from the filename
    [year, month_day_id] = filename |> Path.split() |> Enum.take(-2)

    # Then extract the month, day and id from the filename itself
    [month, day, id_with_md] = String.split(month_day_id, "-", parts: 3)

    # Remove .md extension from id
    id = Path.rootname(id_with_md)

    # Build a Date struct from the path information
    date = Date.from_iso8601!("#{year}-#{month}-#{day}")

    # Get all attributes from the contents
    contents = parse_contents(File.read!(filename))

    # Finally build the post struct
    struct!(__MODULE__, [id: id, date: date] ++ contents)
  end

  defp parse_contents(contents) do
    # Split contents into  ["==title==\n", "this title", "==tags==\n", "this, tags", ...]
    parts = Regex.split(~r/^==(\w+)==\n/m, contents, include_captures: true, trim: true)

    # Now chunk each attr and value into pairs and parse them
    for [attr_with_equals, value] <- Enum.chunk_every(parts, 2) do
      [_, attr, _] = String.split(attr_with_equals, "==")
      attr = String.to_atom(attr)
      {attr, parse_attr(attr, value)}
    end
  end

  defp parse_attr(:title, value),
    do: value |> String.trim()

  defp parse_attr(:author, value),
    do: value |> String.trim()

  defp parse_attr(:description, value),
    do: value |> String.trim()

  defp parse_attr(:body, value),
    do: value |> String.trim()

  defp parse_attr(:tags, value),
    do: value |> String.split(",") |> Enum.map(&String.trim/1) |> Enum.sort()
end

lib/shenanigans_web/controllers/blog_controller.ex
defmodule ShenanigansWeb.BlogController do
  use ShenanigansWeb, :controller

  alias Shenanigans.Blog

  def index(conn, _params) do
    posts = Blog.all_posts()

    render(conn, "index.html", posts: posts)
  end

  def show(conn, %{"slug" => slug}) do
    post = Blog.get_post(slug)

    render(conn, "show.html", post: post)
  end
end

lib/shenanigans_web/controllers/tag_controller.ex
defmodule ShenanigansWeb.TagController do
  use ShenanigansWeb, :controller

  alias Shenanigans.Blog

  def index(conn, %{"tag" => tag}) do
    posts = Blog.get_posts_by_tag!(tag)

    render(conn, "index.html", posts: posts)
  end
end

lib/shenanigans_web/views/blog_view.ex
defmodule ShenanigansWeb.BlogView do
  use ShenanigansWeb, :view

  alias Shenanigans.Blog.Highlighter

  def format_date(date) do
    case Timex.format(date, "%d %B %Y", :strftime) do
      {:ok, formatted} ->
        formatted

      {:error, _reason} ->
        "Unknown"
    end
  end

  def markdown(content) do
    content
    |> Earmark.as_html!()
    |> Highlighter.highlight()
    |> raw
  end
end

lib/shenanigans_web/views/error_view.ex
defmodule ShenanigansWeb.ErrorView do
  use ShenanigansWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/shenanigans_web/views/layout_view.ex
defmodule ShenanigansWeb.LayoutView do
  use ShenanigansWeb, :view
end

lib/shenanigans_web/views/tag_view.ex
defmodule ShenanigansWeb.TagView do
  use ShenanigansWeb, :view

  def format_date(date) do
    case Timex.format(date, "%d %B %Y", :strftime) do
      {:ok, formatted} ->
        formatted

      {:error, _reason} ->
        "Unknown"
    end
  end
end

lib/shenanigans_web/templates/blog/_tags.html.eex
<%= for tag <- @tags do %>
    <%= link "##{tag}", to: Routes.tag_path(@conn, :index, tag) %>
<% end %>

lib/shenanigans_web/templates/blog/index.html.eex
<section>
  <h2>Blog</h2>
  <%= for post <- @posts do %>
    <%= link post.title, to: Routes.post_path(@conn, :show, post) %>
    <%= render "_tags.html", conn: @conn, tags: post.tags %>
    <p><%= post.description %></p>
  <% end %>
</section>

lib/shenanigans_web/templates/blog/show.html.eex
<section>
    <h1><%= @post.title %></h1>
    <p><%= format_date(@post.date) %></p>
    <%= render "_tags.html", conn: @conn, tags: @post.tags %>
    <%= markdown(@post.body) %>
</section>

lib/shenanigans_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#502e71" />
    <meta property="og:url" content="https://www.hansjhoffman.dev" />
    <meta property="og:title" content="" />
    <meta property="og:description" content="" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="<%= Routes.static_path(@conn, "/images/logo.svg") %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="640" />
    <meta name="twitter:site" content="https://www.hansjhoffman.dev" />
    <meta name="twitter:card" content="" />
    <meta name="twitter:image" content="<%= Routes.static_path(@conn, "/images/logo.svg") %>" />
    <title><%= assigns[:page_title] || "Blog · Hans Hoffman" %></title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i&display=swap" />
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
    <link rel="icon" href="<%= Routes.static_path(@conn, "/favicon.ico") %>" />
    <link rel="alternate" href="<%= Routes.static_path(@conn, "/rss.xml") %>" type="application/rss+xml" />
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header class="">

    </header>
    <main role="main" class="">
      <p class="alert alert-info" role="alert">Website is a WIP but content is still good :)</p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer>
      Made with <a href="https://phoenixframework.org/" class="">Elixir + Phoenix</a> & <a href="https://elm-lang.org/" class="">Elm</a>
    </footer>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/shenanigans_web/templates/tag/index.html.eex
<section>
  <h2>Listing posts tagged with tag</h2>
  <%= for post <- @posts do %>
    <%= link post.title, to: Routes.post_path(@conn, :show, post) %>
    <p><%= post.tags %></p>
    <p><%= post.description %></p>
  <% end %>
</section>